### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by baohouse** [a-ignatov-parc/requirejs-sandbox#27]
My use case involves requirejs being loaded into a namespace, so I wrap the requirejs-sandbox loading script and eval() it

``` javascript
(function(define, require, requirejs) {
  REQUIREJS_SANDBOX_CODE
}(myApp.define, myApp.require, myApp.requirejs));
```

This is necessary to ensure that AMD-compatible libraries on our client's page do not register themselves into our requirejs when they need those libraries to load in global scope, while my widget can load its libraries AND register it into requirejs.

I don't know if that affects the requirejsSandbox code in weird ways, but I run into an issue where after I call requirejsSandbox.set(), the sandboxManager returns null for this module:
define('helpers/resolvers/iframeResolver'...

I traced the dependencies and found a circular dependency:
'helpers/resolvers/iframeResolver' depends on 'sandbox-manager',
'sandbox-manager' depends on 'helpers/require', and finally
'helpers/require' depends on 'helpers/resolvers/iframeResolver' again

I'm wondering if this might be a problem.

**Comment by a-ignatov-parc** [comment]
`requirejs-sandbox` defines as UMD so if it won't find global `define` it will export its api to global variable `requirejsSandbox` and will be available as `requirejsSandbox.manager` so you don't need to do some extra defining.

And thanks for posting bug with `iframeResolver`. Strange that test haven't reveal it. Will check it later. To workaround this issue you can specify path to require.js for sandbox in params:

``` javascript
requirejsSandbox.set('TestApp', {
    requireUrl: '/static/js/libs/require.min.js',
    ...
});
```

P.S. Can you tell me more about your require.js configuration? When you include require.js file? When and how you namespacing it?

**Comment by baohouse** [comment]
Hi Anton,

There are two situations that we have to work around:
1. A client has AMD-compatible libraries, but they don't use RequireJS...
if I load RequireJS onto the page, it breaks their libraries.
2. Another client has an old version of RequireJS; if we load our version
of RequireJS, it will not override (this is why I posted to the RequireJS
issues). Our other Javascript files will register themselves with the old
version of RequireJS, which causes problems if it has a different base path.

So given those two situations, we had to load RequireJS into a namespace
(i.e. load it into MyApp object as MyApp.requirejs). It's simply using
XMLHTTPRequest to retrieve the file, wrap the result in a closure, and then
eval() it. Here's the source:

```
  MyApp.wrapLoadScript = function (url, callback, wrapFunction) {
    var xhr = new XMLHttpRequest();
    var status;
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4) {
        status = xhr.status || 0;
        if (status > 399 && status < 600) {
          // An http 4xx or 5xx error. Signal an error
        } else {
          response = xhr.responseText;
          if (response) {
            if (typeof wrapFunction === 'function') {
              eval(wrapFunction(response)+'\n'+
                '//# sourceURL=' + url.replace(/^[a-z]*:?\/\//g, 'http://
')+'\n'
              );
            } else {
              eval(response);
            }
          }
          if (typeof callback === 'function') {
            callback();
          }
        }
      }
    };
    xhr.open("GET", url, true);
    xhr.send();
  };

  MyApp.wrapLoadScript( 'fullpath.com/js/ext/require-2.1.14.min.js',
function () {
    require = MyApp.require;
    define  = MyApp.define;
    require(['fullpath.com/js/ext/requirejs-sandbox.js'],
      function (requirejsSandbox) {
        requirejsSandbox.set('MyApp', {
          ... SANDBOX_CONFIG ...
        });
      }
    );
  }, function (scriptSource) {
    return '(function(define, require, requirejs){\n'+
      scriptSource+'\n'+
      'MyApp.define = define;\n'+
      'MyApp.require = require;\n'+
      'MyApp.requirejs = requirejs;\n'+
    '}).call(MyApp, MyApp.define, MyApp.require, MyApp.requirejs);\n';
  });
```

On Wed, Jul 16, 2014 at 1:22 AM, Anton Ignatov notifications@github.com
wrote:

> requirejs-sandbox defines as UMD so if it won't find global define it
> will export its api to global variable requirejsSandbox so you don't need
> to do some extra defining.
> 
> And thanks for posting bug with iframeResolver. Strange that test haven't
> reveal it. Will check it later. To workaround this issue you can specify
> path to require.js for sandbox in params:
> 
> requirejsSandbox.set('TestApp', {
>     requireUrl: '/static/js/libs/require.min.js',
>     ...
> });
> 
> P.S. Can you tell me more about your require.js configuration? When you
> include require.js file? When and how you namespacing it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a-ignatov-parc/requirejs-sandbox/issues/27#issuecomment-49136322
> .

## 

Bao Ngo
Front End Developer

Planwise
300 Brannan Street, Suite 610
San Francisco, California 94107
(415) 830-3777

**Comment by a-ignatov-parc** [comment]
I see. This is exact the one of use cases this library was created to handle with :)

So here is what you should try:
1. Add to your page `build/requirejs-sandbox.js` file. This action will register module with `requirejs-sandbox` name if require.js will be available on target page (even if it's old version) and this module don't need any extra configuration.
   
   > Don't use your `MyApp.wrapLoadScript`. 
2. Require `requirejs-sandbox` module and create sandbox with the exact version of require.js you need.
   
   ``` javascript
   // Here you using require function from old require.js
   require(['requirejs-sandbox'], function(requirejsSandbox) {
       requirejsSandbox.set('MyApp', {
           requireUrl: 'fullpath.com/js/ext/require-2.1.14.min.js', // require.js you need to use
   
           // Sandbox's require.js config you need
           requireConfig: {
               baseUrl: 'app',
               paths: {
                   'backbone': '/static/js/libs/backbone',
                   'jquery': '/static/js/libs/jquery/jquery.min',
                   'underscore': '/static/js/libs/underscore.min'
               },
               shim: {
                   underscore: {
                       exports: '_'
                   },
                   backbone: {
                       deps: ['underscore', 'jquery'],
                       exports: 'Backbone'
                   }
               }
           },
           success: function(require, define) {
               // Here everything is ready and require and define passed in arguments is now what you should use. they will point to sandbox's require.js that you set in requireUrl param
               require([my/module/which/need/require/2.0/to/work], function(myModule) {
                   myModule.init();
               });
           }
       });
   });
   ```

If something will go wrong please tell me what is the version of old require.js is used on your page. And if there will be any errors tell me about them too.

**Comment by a-ignatov-parc** [comment]
And i forget to mention that if there is no require.js on the page then code example in step 2 above simply transforms to:

``` javascript
window.requirejsSandbox.manager.set('MyApp', {
    requireUrl: 'fullpath.com/js/ext/require-2.1.14.min.js',
    requireConfig: { ... },
    success: function(require, define) {
        require([my/module/which/need/require/2.0/to/work], function(myModule) {
            myModule.init();
        });
    }
});
```
